# Generated by Django 2.0.7 on 2019-12-13 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ename', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ISSUE', '문제'), ('SOLUTION', '조치')], max_length=1)),
                ('content', models.CharField(max_length=100)),
                ('econtent', models.CharField(blank=True, max_length=100)),
                ('businessunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downtimeML.BusinessUnit')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('businessunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downtimeML.BusinessUnit')),
            ],
        ),
        migrations.CreateModel(
            name='MachineGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('ename', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downtimeML.Category')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downtimeML.Line')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='machinegroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downtimeML.MachineGroup'),
        ),
        migrations.AddField(
            model_name='issue',
            name='machinetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='downtimeML.MachineType'),
        ),
    ]
